/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;

/**
 *
 * @author vomkh
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraphic = new javax.swing.JPanel();
        Graphic = new javax.swing.JLabel();
        informationPannel = new javax.swing.JPanel();
        goBackButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        confirmPasswordFill = new javax.swing.JTextField();
        userNameFill = new javax.swing.JTextField();
        loginFailLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordFill1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGraphic.setPreferredSize(new java.awt.Dimension(350, 409));
        panelGraphic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Graphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        panelGraphic.add(Graphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 480, 610));

        getContentPane().add(panelGraphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        informationPannel.setBackground(new java.awt.Color(51, 153, 255));
        informationPannel.setForeground(new java.awt.Color(51, 102, 255));
        informationPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackButton.setText("Go Back");
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackButtonMouseClicked(evt);
            }
        });
        informationPannel.add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 40));

        closeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        informationPannel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 30, 30));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Forgot Password");
        informationPannel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 404, 67));

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("Username");
        informationPannel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_____________________________________________________________________");
        informationPannel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 360, 30));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Phone Number");
        informationPannel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_____________________________________________________________________");
        informationPannel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 370, 30));

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(51, 153, 255));
        loginButton.setText("Set New Password");
        loginButton.setToolTipText("");
        loginButton.setBorder(null);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        informationPannel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 350, 40));

        confirmPasswordFill.setBackground(new java.awt.Color(51, 153, 255));
        confirmPasswordFill.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordFill.setBorder(null);
        confirmPasswordFill.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        confirmPasswordFill.setSelectionColor(new java.awt.Color(255, 255, 255));
        confirmPasswordFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFillActionPerformed(evt);
            }
        });
        informationPannel.add(confirmPasswordFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 330, 30));

        userNameFill.setBackground(new java.awt.Color(51, 153, 255));
        userNameFill.setForeground(new java.awt.Color(255, 255, 255));
        userNameFill.setBorder(null);
        userNameFill.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        informationPannel.add(userNameFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 330, 20));

        loginFailLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginFailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginFailLabel.setText(" ");
        informationPannel.add(loginFailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, -1));

        passwordLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setText("New Password");
        informationPannel.add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_____________________________________________________________________");
        informationPannel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 370, 30));

        passwordFill1.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill1.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill1.setBorder(null);
        passwordFill1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill1.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill1ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 330, 30));

        getContentPane().add(informationPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -10, 410, 480));

        setSize(new java.awt.Dimension(781, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseClicked
        try {
            this.dispose();
            new Login().setVisible(true);
        } catch (IOException ex) {
           
        }
    }//GEN-LAST:event_goBackButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        String username = userNameFill.getText();
        String password = confirmPasswordFill.getText();
        String admin = "admin";
        String user = "user";
        if (username.equals(admin) && password.equals(admin)) {
            this.dispose();
            new QuerryForm().setVisible(true);
        } else if (username.equals(user) && password.equals(user)) {
            this.dispose();
            new Dashboard().setVisible(true);
        } else {
            loginFailLabel.setText("Wrong Password Or Username");// TODO add your handling code here:
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

    }//GEN-LAST:event_loginButtonActionPerformed

    private void confirmPasswordFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFillActionPerformed

    private void passwordFill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Graphic;
    private javax.swing.JLabel closeButton;
    private javax.swing.JTextField confirmPasswordFill;
    private javax.swing.JLabel goBackButton;
    private javax.swing.JPanel informationPannel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginFailLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel panelGraphic;
    private javax.swing.JTextField passwordFill1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField userNameFill;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
