/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;

/**
 *
 * @author vomkh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     * @throws java.io.IOException
     */
    public Login() throws IOException {
        initComponents();
        this.setTitle("Portal Application For Motor Servicing At Home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGraphic = new javax.swing.JPanel();
        Graphic = new javax.swing.JLabel();
        informationPannel = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rememberMeBox = new javax.swing.JCheckBox();
        forgotMeLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        passwordFill = new javax.swing.JTextField();
        userNameFill = new javax.swing.JTextField();
        signUpLabel = new javax.swing.JLabel();
        dontHaveAccLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGraphic.setPreferredSize(new java.awt.Dimension(350, 409));
        panelGraphic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Graphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        panelGraphic.add(Graphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 480, 610));

        getContentPane().add(panelGraphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        informationPannel.setBackground(new java.awt.Color(51, 153, 255));
        informationPannel.setForeground(new java.awt.Color(51, 102, 255));
        informationPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        informationPannel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 6, 53, 31));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("LOGIN");
        informationPannel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 404, 67));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Portal Application For Motor Servicing At Home ");
        informationPannel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 30));

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("Username");
        informationPannel.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_____________________________________________________________________");
        informationPannel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 360, 30));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        informationPannel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_____________________________________________________________________");
        informationPannel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 370, 30));

        rememberMeBox.setBackground(new java.awt.Color(51, 153, 255));
        rememberMeBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rememberMeBox.setForeground(new java.awt.Color(255, 255, 255));
        rememberMeBox.setText("Remember Me");
        rememberMeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberMeBoxActionPerformed(evt);
            }
        });
        informationPannel.add(rememberMeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, -1));

        forgotMeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        forgotMeLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotMeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotMeLabel.setText("Forgot Password? ");
        informationPannel.add(forgotMeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.setToolTipText("");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        informationPannel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 350, 40));

        passwordFill.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill.setBorder(null);
        passwordFill.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFillActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 330, 30));

        userNameFill.setBackground(new java.awt.Color(51, 153, 255));
        userNameFill.setForeground(new java.awt.Color(255, 255, 255));
        userNameFill.setBorder(null);
        userNameFill.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        informationPannel.add(userNameFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 330, 20));

        signUpLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(255, 255, 255));
        signUpLabel.setText("Sign Up");
        informationPannel.add(signUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 50, -1));

        dontHaveAccLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dontHaveAccLabel.setForeground(new java.awt.Color(204, 204, 204));
        dontHaveAccLabel.setText("Don't have a account ?");
        informationPannel.add(dontHaveAccLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 150, -1));

        getContentPane().add(informationPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -10, 410, 480));

        setSize(new java.awt.Dimension(780, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void rememberMeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberMeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberMeBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Graphic;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel dontHaveAccLabel;
    private javax.swing.JLabel forgotMeLabel;
    private javax.swing.JPanel informationPannel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel panelGraphic;
    private javax.swing.JTextField passwordFill;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JCheckBox rememberMeBox;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userNameFill;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
