/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;

/**
 *
 * @author vomkh
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form OrderHistory
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationPannel = new javax.swing.JPanel();
        goBackButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginFailLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordFill1 = new javax.swing.JTextField();
        passwordLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loginLabel1 = new javax.swing.JLabel();
        passwordLabel4 = new javax.swing.JLabel();
        passwordFill3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        loginLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informationPannel.setBackground(new java.awt.Color(51, 153, 255));
        informationPannel.setForeground(new java.awt.Color(51, 102, 255));
        informationPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackButton.setText("Go Back");
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackButtonMouseEntered(evt);
            }
        });
        informationPannel.add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 40));

        closeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        informationPannel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 30));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("ORDER");
        informationPannel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 400, 67));

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(51, 153, 255));
        loginButton.setText("ADD SERVICE");
        loginButton.setToolTipText("");
        loginButton.setBorder(null);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        informationPannel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 340, 40));

        loginFailLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginFailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginFailLabel.setText(" ");
        informationPannel.add(loginFailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_____________________________________________________________________");
        informationPannel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 370, 30));

        passwordFill1.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill1.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill1.setBorder(null);
        passwordFill1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill1.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill1ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 330, 30));

        passwordLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel3.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel3.setText("Service ID");
        informationPannel.add(passwordLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 130, 20));

        jTable1.setBackground(new java.awt.Color(51, 102, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Service Name", "Vehicle ID"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        informationPannel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 350, 260));

        loginLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel1.setText("SERVICE");
        informationPannel.add(loginLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 830, 67));

        passwordLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel4.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel4.setText("Vehicle ID");
        informationPannel.add(passwordLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 20));

        passwordFill3.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill3.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill3.setBorder(null);
        passwordFill3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill3.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill3ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_____________________________________________________________________");
        informationPannel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 370, 30));

        loginLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel2.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel2.setText("USE SERVICE");
        informationPannel.add(loginLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 400, 67));

        jTable2.setBackground(new java.awt.Color(51, 102, 255));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service ID", "Service_Name", "Cost", "Descritition"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Cost");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Descritition");
        }

        informationPannel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 820, 210));

        getContentPane().add(informationPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 790));

        setSize(new java.awt.Dimension(840, 780));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseClicked
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_goBackButtonMouseClicked

    private void goBackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackButtonMouseEntered

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked

    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill1ActionPerformed

    private void passwordFill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel goBackButton;
    private javax.swing.JPanel informationPannel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginFailLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JLabel loginLabel2;
    private javax.swing.JTextField passwordFill1;
    private javax.swing.JTextField passwordFill3;
    private javax.swing.JLabel passwordLabel3;
    private javax.swing.JLabel passwordLabel4;
    // End of variables declaration//GEN-END:variables
}
