/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import motorservice.Customer;
import motorservice.Order;
import motorservice.OrderDAO;
import motorservice.OrderStatus;
import motorservice.OrderStatusDAO;

/**
 *
 * @author nguyenhoanggiaan
 */
public class PlaceOrder extends javax.swing.JFrame implements ActionListener {
    OrderStatusDAO daoOrderStatus = new OrderStatusDAO();
    OrderDAO daoOrder = new OrderDAO();
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        setLocationRelativeTo(null);
        getDataCombobox();
        btncancel.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtenddate = new javax.swing.JTextField();
        btnaddorder = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxorderstatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbresult = new javax.swing.JTable();
        txtvehicleplatenumber = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();
        btnshowall = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtstaffid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Order");

        jLabel2.setText("Customer ID:");

        jLabel3.setText("Vehicle Plate Number:");

        jLabel5.setText("Start date:");

        jLabel6.setText("End date:");

        btnaddorder.setText("Add order");
        btnaddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddorderActionPerformed(evt);
            }
        });

        jLabel7.setText("Order status:");

        tbresult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Plate number", "Start date", "End date", "Order status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbresult);

        btndelete.setText("Delete ");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnshowall.setText("Show all");

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Staff ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtvehicleplatenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(txtcustomerid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtstartdate)
                    .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxorderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstaffid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnshowall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaddorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(333, 333, 333))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcustomerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddorder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtvehicleplatenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshowall)
                    .addComponent(jLabel5)
                    .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxorderstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstatus)
                    .addComponent(btncancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnaddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddorderActionPerformed
        if(!checkValidInput()){
            JOptionPane.showMessageDialog(this,"You need to enter all information!");
        }else{
            try {
                Order o = getModel();
                System.out.println("=>"+o.toString());
                if(daoOrder.add(o)>0){
                    lblstatus.setText("Saved successfully");
                    addSQL(o);
                    updateDataIntoTable();
                    resetForm();
                }
            } catch (ParseException ex) {
                Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        resetForm();
    }//GEN-LAST:event_btnaddorderActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if(txtcustomerid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"You need to enter Customer ID to search his/her order !");
        }else{
            if(daoOrder.delete(txtcustomerid.getText().trim())>0){
                lblstatus.setText("Delete Successfully Order of customer "+ txtcustomerid.getText());
                deleteSQL(txtcustomerid.getText());
                updateDataIntoTable();
                resetForm();
            }else{
                lblstatus.setText("Can not found Order of Customer "+ txtcustomerid.getText());
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed
    public void setModel(Order o){
        txtcustomerid.setText(o.getCustomerId());
        txtstaffid.setText(o.getStaffId());
        txtvehicleplatenumber.setText(o.getPlateNumber());
        txtstartdate.setText(date_format.format(o.getStartDate()));
        txtenddate.setText(date_format.format(o.getEndDate()));
        cbxorderstatus.setSelectedItem(o.getOrderStatus());
    }
    public Order getModel() throws ParseException{
        Order o = new Order();
        o.setCustomerId(txtcustomerid.getText().trim());
        o.setStaffId(txtstaffid.getText().trim());
        o.setPlateNumber(txtvehicleplatenumber.getText().trim());
        o.setStartDate(date_format.parse(txtstartdate.getText().trim()));
        o.setEndDate(date_format.parse(txtenddate.getText().trim()));
        o.setOrderStatus((OrderStatus)cbxorderstatus.getSelectedItem());
        return o;
    }
    public boolean checkValidInput(){
        if(txtcustomerid.getText().isEmpty()
                ||txtstaffid.getText().isEmpty()
                ||txtvehicleplatenumber.getText().isEmpty()
                ||txtstartdate.getText().isEmpty()
                ||txtenddate.getText().isEmpty()
                ){
            return false;
        }
        return true;
    }
    
    public void getDataCombobox(){
        DefaultComboBoxModel<OrderStatus> model 
                = (DefaultComboBoxModel) cbxorderstatus.getModel();
        for(OrderStatus os : daoOrderStatus.getAllOrderStatus()){
            model.addElement(os);
        }
    }
    
    public void resetForm(){
        txtcustomerid.setText("");
        txtstaffid.setText("");
        txtvehicleplatenumber.setText("");
        txtstartdate.setText("");
        txtenddate.setText("");
        cbxorderstatus.setSelectedIndex(0);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddorder;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnshowall;
    private javax.swing.JComboBox<String> cbxorderstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable tbresult;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtstartdate;
    private javax.swing.JTextField txtvehicleplatenumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btncancel)){
            btnCancelClick();
        }
    }
    
    public void btnCancelClick(){
        new MenuScreen().setVisible(true);
        this.dispose();
    }
    
    public void addSQL(Order o){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "INSERT INTO Order (Start_Date,End_Date,Order_Status,Customer_ID,Staff_ID) VALUES (" 

                        + "'"+o.getStartDate()+"'" + ","
                        + "'"+o.getEndDate()+"'" + "," 
                        + "'"+o.getOrderStatus()+"'" + "," 
                        + "'" + o.getCustomerId()+"'" + "," 
                        + "'"+o.getStaffId()+"'" + ")";
                stmt.executeQuery(SQL);
            } catch (SQLException e) { 
            }
    }
    
    public void deleteSQL(String customerId){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "DELETE FROM Order WHERE Customer_ID =" + "'" + customerId + "'";
                stmt.executeQuery(SQL);
            } catch (SQLException e) { 
            }
    }
    
    public void updateDataIntoTable(){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "Select Order_ID,Start_Date,End_Date,Order_Status,Customer_ID,Staff_ID FROM Order";
                ResultSet rs = stmt.executeQuery(SQL);
                DefaultTableModel  tbModel = (DefaultTableModel) tbresult.getModel();
                tbModel.setRowCount(0);
                Object[] rowData = new Object[5];
                
                while(rs.next()){
                    rowData[0] = rs.getString("Order_ID");
                    rowData[1] = rs.getString("Start_Date");
                    rowData[2] = rs.getString("End_Date");
                    rowData[3] = rs.getString("Order_Status");
                    rowData[4] = rs.getFloat("Customer_ID");
                    rowData[4] = rs.getFloat("Staff_ID");
                    tbModel.addRow(rowData);
                }
            } catch (SQLException e) { 
            }
    }
}
