/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import motorservice.Customer;
import motorservice.Order;
import motorservice.OrderDAO;
import motorservice.OrderStatus;
import motorservice.OrderStatusDAO;

/**
 *
 * @author nguyenhoanggiaan
 */
public class PlaceOrder extends javax.swing.JFrame implements ActionListener {
    OrderStatusDAO daoOrderStatus = new OrderStatusDAO();
    OrderDAO daoOrder = new OrderDAO();
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        setLocationRelativeTo(null);
        getDataCombobox();
        btncancel.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbresult = new javax.swing.JTable();
        lblstatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        closeButton1 = new javax.swing.JLabel();
        btnshowall = new javax.swing.JButton();
        btnaddorder = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstaffid = new javax.swing.JTextField();
        txtvehicleplatenumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxorderstatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtenddate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        closeButton2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbresult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Plate number", "Start date", "End date", "Order status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbresult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 263, 790, 295));
        getContentPane().add(lblstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 564, 234, -1));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 20));

        closeButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton1.setForeground(new java.awt.Color(255, 255, 255));
        closeButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton1.setText("X");
        closeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButton1MouseClicked(evt);
            }
        });
        jPanel1.add(closeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 20));

        btnshowall.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnshowall.setForeground(new java.awt.Color(51, 153, 255));
        btnshowall.setText("Show All");
        jPanel1.add(btnshowall, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 84, -1));

        btnaddorder.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnaddorder.setForeground(new java.awt.Color(51, 153, 255));
        btnaddorder.setText("Add Order");
        btnaddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        btndelete.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(51, 153, 255));
        btndelete.setText("Delete ");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 84, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtcustomerid.setBackground(new java.awt.Color(51, 153, 255));
        txtcustomerid.setForeground(new java.awt.Color(255, 255, 255));
        txtcustomerid.setBorder(null);
        jPanel1.add(txtcustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 272, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Staff ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        txtstaffid.setBackground(new java.awt.Color(51, 153, 255));
        txtstaffid.setForeground(new java.awt.Color(255, 255, 255));
        txtstaffid.setBorder(null);
        jPanel1.add(txtstaffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 272, -1));

        txtvehicleplatenumber.setBackground(new java.awt.Color(51, 153, 255));
        txtvehicleplatenumber.setForeground(new java.awt.Color(255, 255, 255));
        txtvehicleplatenumber.setBorder(null);
        jPanel1.add(txtvehicleplatenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 272, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Order Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        cbxorderstatus.setBackground(new java.awt.Color(51, 153, 255));
        cbxorderstatus.setForeground(new java.awt.Color(255, 255, 255));
        cbxorderstatus.setBorder(null);
        jPanel1.add(cbxorderstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Start Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtstartdate.setBackground(new java.awt.Color(51, 153, 255));
        txtstartdate.setForeground(new java.awt.Color(255, 255, 255));
        txtstartdate.setBorder(null);
        jPanel1.add(txtstartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 272, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("End Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        txtenddate.setBackground(new java.awt.Color(51, 153, 255));
        txtenddate.setForeground(new java.awt.Color(255, 255, 255));
        txtenddate.setBorder(null);
        jPanel1.add(txtenddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 271, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Plate Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btncancel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btncancel.setForeground(new java.awt.Color(51, 153, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, -1, -1));

        closeButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton2.setForeground(new java.awt.Color(255, 255, 255));
        closeButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton2.setText("X");
        closeButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButton2MouseClicked(evt);
            }
        });
        jPanel1.add(closeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_________________________________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________________________________________________________");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_________________________________________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("_________________________________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("_________________________________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnaddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddorderActionPerformed
        if(!checkValidInput()){
            JOptionPane.showMessageDialog(this,"You need to enter all information!");
        }else{
            try {
                Order o = getModel();
                System.out.println("=>"+o.toString());
                if(daoOrder.add(o)>0){
                    lblstatus.setText("Saved successfully");
                    addSQL(o);
                    updateDataIntoTable();
                    resetForm();
                }
            } catch (ParseException ex) {
                Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        resetForm();
    }//GEN-LAST:event_btnaddorderActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if(txtcustomerid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"You need to enter Customer ID to search his/her order !");
        }else{
            if(daoOrder.delete(txtcustomerid.getText().trim())>0){
                lblstatus.setText("Delete Successfully Order of customer "+ txtcustomerid.getText());
                deleteSQL(txtcustomerid.getText());
                updateDataIntoTable();
                resetForm();
            }else{
                lblstatus.setText("Can not found Order of Customer "+ txtcustomerid.getText());
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButton1MouseClicked

    private void closeButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButton2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButton2MouseClicked
    public void setModel(Order o){
        txtcustomerid.setText(o.getCustomerId());
        txtstaffid.setText(o.getStaffId());
        txtvehicleplatenumber.setText(o.getPlateNumber());
        txtstartdate.setText(date_format.format(o.getStartDate()));
        txtenddate.setText(date_format.format(o.getEndDate()));
        cbxorderstatus.setSelectedItem(o.getOrderStatus());
    }
    public Order getModel() throws ParseException{
        Order o = new Order();
        o.setCustomerId(txtcustomerid.getText().trim());
        o.setStaffId(txtstaffid.getText().trim());
        o.setPlateNumber(txtvehicleplatenumber.getText().trim());
        o.setStartDate(date_format.parse(txtstartdate.getText().trim()));
        o.setEndDate(date_format.parse(txtenddate.getText().trim()));
        o.setOrderStatus((OrderStatus)cbxorderstatus.getSelectedItem());
        return o;
    }
    public boolean checkValidInput(){
        if(txtcustomerid.getText().isEmpty()
                ||txtstaffid.getText().isEmpty()
                ||txtvehicleplatenumber.getText().isEmpty()
                ||txtstartdate.getText().isEmpty()
                ||txtenddate.getText().isEmpty()
                ){
            return false;
        }
        return true;
    }
    
    public void getDataCombobox(){
        DefaultComboBoxModel<OrderStatus> model 
                = (DefaultComboBoxModel) cbxorderstatus.getModel();
        for(OrderStatus os : daoOrderStatus.getAllOrderStatus()){
            model.addElement(os);
        }
    }
    
    public void resetForm(){
        txtcustomerid.setText("");
        txtstaffid.setText("");
        txtvehicleplatenumber.setText("");
        txtstartdate.setText("");
        txtenddate.setText("");
        cbxorderstatus.setSelectedIndex(0);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddorder;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnshowall;
    private javax.swing.JComboBox<String> cbxorderstatus;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel closeButton1;
    private javax.swing.JLabel closeButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable tbresult;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtstartdate;
    private javax.swing.JTextField txtvehicleplatenumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btncancel)){
            btnCancelClick();
        }
    }
    
    public void btnCancelClick(){
        new MenuScreen().setVisible(true);
        this.dispose();
    }
    
    public void addSQL(Order o){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "INSERT INTO Order (Start_Date,End_Date,Order_Status,Customer_ID,Staff_ID) VALUES (" 

                        + "'"+o.getStartDate()+"'" + ","
                        + "'"+o.getEndDate()+"'" + "," 
                        + "'"+o.getOrderStatus()+"'" + "," 
                        + "'" + o.getCustomerId()+"'" + "," 
                        + "'"+o.getStaffId()+"'" + ")";
                stmt.executeQuery(SQL);
            } catch (SQLException e) { 
            }
    }
    
    public void deleteSQL(String customerId){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "DELETE FROM Order WHERE Customer_ID =" + "'" + customerId + "'";
                stmt.executeQuery(SQL);
            } catch (SQLException e) { 
            }
    }
    
    public void updateDataIntoTable(){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "Select Order_ID,Start_Date,End_Date,Order_Status,Customer_ID,Staff_ID FROM Order";
                ResultSet rs = stmt.executeQuery(SQL);
                DefaultTableModel  tbModel = (DefaultTableModel) tbresult.getModel();
                tbModel.setRowCount(0);
                Object[] rowData = new Object[5];
                
                while(rs.next()){
                    rowData[0] = rs.getString("Order_ID");
                    rowData[1] = rs.getString("Start_Date");
                    rowData[2] = rs.getString("End_Date");
                    rowData[3] = rs.getString("Order_Status");
                    rowData[4] = rs.getFloat("Customer_ID");
                    rowData[4] = rs.getFloat("Staff_ID");
                    tbModel.addRow(rowData);
                }
            } catch (SQLException e) { 
            }
    }
}
