/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import motorservice.ColorDAO;
import motorservice.Color;
import motorservice.Vehicle;
import motorservice.VehicleDAO;
import motorservice.VehicleStatus;
import motorservice.VehicleStatusDAO;
/**
 *
 * @author nguyenhoanggiaan
 */
public class VehicleManagement extends javax.swing.JFrame implements ActionListener{
    ColorDAO daoColor = new ColorDAO();
    VehicleDAO daoVehicle = new VehicleDAO();
    VehicleStatusDAO daoVehicleStatus = new VehicleStatusDAO();
    /**
     * Creates new form VehicleManagement
     */
    public VehicleManagement() {
        initComponents();
        setLocationRelativeTo(null);
        getDataCombobox();
        btncancel.addActionListener(this);
    }
    public void getDataCombobox(){
        DefaultComboBoxModel<Color> model 
                = (DefaultComboBoxModel) cbxcolor.getModel();
        for(Color color : daoColor.getAllColor()){
            model.addElement(color);
        }
        
        DefaultComboBoxModel<VehicleStatus> modelStatus 
                = (DefaultComboBoxModel) cbxstatus.getModel();
        for(VehicleStatus st : daoVehicleStatus.getAllStatus()){
            modelStatus.addElement(st);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbresult = new javax.swing.JTable();
        lblstatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnshowall = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnaddnew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtplatenumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtbrand = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxcolor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtrentcost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxstatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbresult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbresult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plate number", "Brand", "Model", "Color", "Rent cost", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbresult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbresultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbresult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 282, 865, 260));

        lblstatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lblstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 554, 288, 26));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VEHICLE MANGETMENT");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 870, -1));

        btncancel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(51, 153, 255));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, -1, -1));

        btnshowall.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnshowall.setForeground(new java.awt.Color(51, 153, 255));
        btnshowall.setText("Show All");
        btnshowall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowallActionPerformed(evt);
            }
        });
        jPanel1.add(btnshowall, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, 90, -1));

        btndelete.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(51, 153, 255));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 250, 100, -1));

        btnaddnew.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnaddnew.setForeground(new java.awt.Color(51, 153, 255));
        btnaddnew.setText("Add New");
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plate Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        txtplatenumber.setBackground(new java.awt.Color(51, 153, 255));
        txtplatenumber.setForeground(new java.awt.Color(255, 255, 255));
        txtplatenumber.setBorder(null);
        txtplatenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplatenumberActionPerformed(evt);
            }
        });
        jPanel1.add(txtplatenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 308, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Brand");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        txtbrand.setBackground(new java.awt.Color(51, 153, 255));
        txtbrand.setForeground(new java.awt.Color(255, 255, 255));
        txtbrand.setBorder(null);
        jPanel1.add(txtbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 308, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Model");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtmodel.setBackground(new java.awt.Color(51, 153, 255));
        txtmodel.setForeground(new java.awt.Color(255, 255, 255));
        txtmodel.setBorder(null);
        jPanel1.add(txtmodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 308, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        cbxcolor.setBackground(new java.awt.Color(51, 153, 255));
        cbxcolor.setForeground(new java.awt.Color(255, 255, 255));
        cbxcolor.setBorder(null);
        jPanel1.add(cbxcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rent Cost");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        txtrentcost.setBackground(new java.awt.Color(51, 153, 255));
        txtrentcost.setForeground(new java.awt.Color(255, 255, 255));
        txtrentcost.setBorder(null);
        jPanel1.add(txtrentcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 308, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        cbxstatus.setBackground(new java.awt.Color(51, 153, 255));
        cbxstatus.setForeground(new java.awt.Color(255, 255, 255));
        cbxstatus.setBorder(null);
        jPanel1.add(cbxstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 258, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("______________________________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 300, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("______________________________________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("______________________________________________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 300, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("______________________________________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 610));

        setSize(new java.awt.Dimension(865, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed
    public Vehicle getModel(){
        Vehicle vc = new Vehicle();
        vc.setPlateNumber(txtplatenumber.getText().trim());
        vc.setBrand(txtbrand.getText().trim());
        vc.setModel(txtmodel.getText().trim());
        vc.setCost(Double.parseDouble(txtrentcost.getText().trim()));
        vc.setColor((Color)cbxcolor.getSelectedItem());
        vc.setStatus((VehicleStatus)cbxstatus.getSelectedItem());
        return vc;
    }
    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed
        if(!checkValidInput()){
            JOptionPane.showMessageDialog(this,"You need to enter all information!");
        }else{
            Vehicle vc = getModel();
            System.out.println("=>"+vc.toString());
            if(daoVehicle.add(vc)>0){
                lblstatus.setText("Saved successfully");
                addSQL(vc);
                updateDataIntoTable();
            }
        }
        resetForm();
    }//GEN-LAST:event_btnaddnewActionPerformed
    
    public void setModel(Vehicle vc){
        txtplatenumber.setText(vc.getPlateNumber());
        txtbrand.setText(vc.getBrand());
        txtmodel.setText(vc.getModel());
        cbxcolor.setSelectedItem(vc.getColor());
        txtrentcost.setText(vc.getCost()+"");
        cbxstatus.setSelectedItem(vc.getStatus());
    }
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if(txtplatenumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"You need to enter plate number to search !");
        }else{            
            if(daoVehicle.delete(txtplatenumber.getText().trim())>0){
                lblstatus.setText("Delete Successfully "+txtplatenumber.getText());
                deleteSQL(txtplatenumber.getText());
                updateDataIntoTable();
                resetForm();
            }else{
                lblstatus.setText("Can not found Customer "+txtplatenumber.getText());
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tbresultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbresultMouseClicked

    }//GEN-LAST:event_tbresultMouseClicked

    private void btnshowallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowallActionPerformed
        updateDataIntoTable();
    }//GEN-LAST:event_btnshowallActionPerformed

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void txtplatenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplatenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplatenumberActionPerformed
    
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnshowall;
    private javax.swing.JComboBox<String> cbxcolor;
    private javax.swing.JComboBox<String> cbxstatus;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JTable tbresult;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtplatenumber;
    private javax.swing.JTextField txtrentcost;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btncancel)){
            btnCancelClick();
        }
    }
    public void btnCancelClick(){
        new MenuScreen().setVisible(true);
        this.dispose();
    }
    
    public void resetForm(){
        txtplatenumber.setText("");
        txtbrand.setText("");
        txtmodel.setText("");
        cbxcolor.setSelectedIndex(0);
        txtrentcost.setText("");
        cbxstatus.setSelectedIndex(0);
    }
    
    public boolean checkValidInput(){
        if(txtplatenumber.getText().isEmpty()
                ||txtbrand.getText().isEmpty()
                ||txtmodel.getText().isEmpty()
                ||txtrentcost.getText().isEmpty()
                ){
            return false;
        }
        return true;
    }
    
    public void fillData(){
        DefaultTableModel  tbModel = (DefaultTableModel) tbresult.getModel();
        tbModel.setRowCount(0);
        for(Vehicle vc : daoVehicle.getAllVehicle()){
            Object[] rowData = new Object[6];
            rowData[0] = vc.getPlateNumber();
            rowData[1] = vc.getBrand();
            rowData[2] = vc.getModel();
            rowData[3] = vc.getColor();
            rowData[4] = vc.getCost();
            rowData[5] = vc.getStatus();
            tbModel.addRow(rowData);
        }
    }
    
    public void addSQL(Vehicle vc){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "INSERT INTO Vehicle (Plate_Number, Brand, Model, Color, Vehicle_Status, Rent_Cost) VALUES (" 
                        + "'" + vc.getPlateNumber()+"'" + "," 
                        + "'"+vc.getBrand()+"'" + ","
                        + "'"+vc.getModel()+"'" + "," 
                        + "'"+vc.getColor()+"'" + "," 
                        + "'"+vc.getStatus()+"'" + ","
                        + "'"+vc.getCost()+"'" + ")";
                stmt.executeQuery(SQL);
            } catch (SQLException e) { 
                System.out.println(e);
            }
    }
    
    public void deleteSQL(String platenumber){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {         
                String SQL = "DELETE FROM Vehicle WHERE Plate_Number =" + "'" + platenumber + "'";
                stmt.executeQuery(SQL);
            } catch (SQLException e) { 
            }
    }
    
    public void updateDataIntoTable(){
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Motorbike_Hiring;user=sa;password=giaan512";
            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
                String SQL = "Select Plate_Number,Brand,Model,Color,Rent_Cost,Vehicle_Status FROM Vehicle";
                ResultSet rs = stmt.executeQuery(SQL);
                DefaultTableModel  tbModel = (DefaultTableModel) tbresult.getModel();
                tbModel.setRowCount(0);
                Object[] rowData = new Object[6];
                
                while(rs.next()){
                    rowData[0] = rs.getString("Plate_Number");
                    rowData[1] = rs.getString("Brand");
                    rowData[2] = rs.getString("Model");
                    rowData[3] = rs.getString("Color");
                    rowData[4] = rs.getFloat("Rent_Cost");
                    rowData[5] = rs.getString("Vehicle_Status");
                    tbModel.addRow(rowData);
                }
            } catch (SQLException e) { 
                System.out.println(e);
            }
    }
}
