/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;

/**
 *
 * @author vomkh
 */
public class VehicleInventory extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public VehicleInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationPannel = new javax.swing.JPanel();
        goBackButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        confirmPasswordFill = new javax.swing.JTextField();
        loginFailLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordFill1 = new javax.swing.JTextField();
        passwordLabel2 = new javax.swing.JLabel();
        passwordLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        passwordFill2 = new javax.swing.JTextField();
        confirmPasswordFill1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loginLabel1 = new javax.swing.JLabel();
        passwordLabel4 = new javax.swing.JLabel();
        passwordFill3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        passwordLabel5 = new javax.swing.JLabel();
        passwordFill4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        informationPannel.setBackground(new java.awt.Color(51, 153, 255));
        informationPannel.setForeground(new java.awt.Color(51, 102, 255));
        informationPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goBackButton.setText("Go Back");
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackButtonMouseEntered(evt);
            }
        });
        informationPannel.add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 40));

        closeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        informationPannel.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 40, 30));

        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("ADD VEHICLE");
        informationPannel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 830, 67));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_____________________________________________________________________");
        informationPannel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 360, 30));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Year");
        informationPannel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 130, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_____________________________________________________________________");
        informationPannel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 370, 30));

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(51, 153, 255));
        loginButton.setText("ADD NEW VEHICLE");
        loginButton.setToolTipText("");
        loginButton.setBorder(null);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        informationPannel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 700, 400, 40));

        confirmPasswordFill.setBackground(new java.awt.Color(51, 153, 255));
        confirmPasswordFill.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordFill.setBorder(null);
        confirmPasswordFill.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        confirmPasswordFill.setSelectionColor(new java.awt.Color(255, 255, 255));
        confirmPasswordFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFillActionPerformed(evt);
            }
        });
        informationPannel.add(confirmPasswordFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 640, 330, 30));

        loginFailLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginFailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginFailLabel.setText(" ");
        informationPannel.add(loginFailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, -1));

        passwordLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setText("Plate Number");
        informationPannel.add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 130, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_____________________________________________________________________");
        informationPannel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 370, 30));

        passwordFill1.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill1.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill1.setBorder(null);
        passwordFill1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill1.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill1ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 330, 30));

        passwordLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel2.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel2.setText("Color");
        informationPannel.add(passwordLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 130, 20));

        passwordLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel3.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel3.setText("Branch");
        informationPannel.add(passwordLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 130, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("_____________________________________________________________________");
        informationPannel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 360, 30));

        passwordFill2.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill2.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill2.setBorder(null);
        passwordFill2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill2.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill2ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 330, 30));

        confirmPasswordFill1.setBackground(new java.awt.Color(51, 153, 255));
        confirmPasswordFill1.setForeground(new java.awt.Color(255, 255, 255));
        confirmPasswordFill1.setBorder(null);
        confirmPasswordFill1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        confirmPasswordFill1.setSelectionColor(new java.awt.Color(255, 255, 255));
        confirmPasswordFill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFill1ActionPerformed(evt);
            }
        });
        informationPannel.add(confirmPasswordFill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 330, 30));

        jTable1.setBackground(new java.awt.Color(51, 102, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehicle_ID", "Model", "Color", "Year"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        informationPannel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 820, 210));

        loginLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel1.setText("VEHICLE INVENTORY");
        informationPannel.add(loginLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 830, 67));

        passwordLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel4.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel4.setText("Vehicle ID");
        informationPannel.add(passwordLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 130, 20));

        passwordFill3.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill3.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill3.setBorder(null);
        passwordFill3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill3.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill3ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 330, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_____________________________________________________________________");
        informationPannel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 370, 30));

        passwordLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel5.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel5.setText("Model");
        informationPannel.add(passwordLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 130, 20));

        passwordFill4.setBackground(new java.awt.Color(51, 153, 255));
        passwordFill4.setForeground(new java.awt.Color(255, 255, 255));
        passwordFill4.setBorder(null);
        passwordFill4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        passwordFill4.setSelectionColor(new java.awt.Color(255, 255, 255));
        passwordFill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFill4ActionPerformed(evt);
            }
        });
        informationPannel.add(passwordFill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 330, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("_____________________________________________________________________");
        informationPannel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 360, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(informationPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(informationPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(840, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseClicked
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_goBackButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked

    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

    }//GEN-LAST:event_loginButtonActionPerformed

    private void confirmPasswordFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFillActionPerformed

    private void passwordFill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill1ActionPerformed

    private void passwordFill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill2ActionPerformed

    private void confirmPasswordFill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFill1ActionPerformed

    private void passwordFill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill3ActionPerformed

    private void passwordFill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFill4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFill4ActionPerformed

    private void goBackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_goBackButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JTextField confirmPasswordFill;
    private javax.swing.JTextField confirmPasswordFill1;
    private javax.swing.JLabel goBackButton;
    private javax.swing.JPanel informationPannel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginFailLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JTextField passwordFill1;
    private javax.swing.JTextField passwordFill2;
    private javax.swing.JTextField passwordFill3;
    private javax.swing.JTextField passwordFill4;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel passwordLabel2;
    private javax.swing.JLabel passwordLabel3;
    private javax.swing.JLabel passwordLabel4;
    private javax.swing.JLabel passwordLabel5;
    // End of variables declaration//GEN-END:variables
}
